// <auto-generated />
using System;
using EDMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EDMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EDMS.Core.Domain.AllergyRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("ConflictingDrugs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AllergenName");

                    b.ToTable("AllergyRegistries");
                });

            modelBuilder.Entity("EDMS.Core.Domain.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.HasIndex("ScheduledTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("EDMS.Core.Domain.Encounter", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualWaitMin")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedDoctorId")
                        .HasColumnType("text");

                    b.Property<string>("AssignedRoom")
                        .HasColumnType("text");

                    b.Property<float?>("BloodPressureDiastolic")
                        .HasColumnType("real");

                    b.Property<float?>("BloodPressureSystolic")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedWaitMin")
                        .HasColumnType("numeric");

                    b.Property<int?>("FinalDisposition")
                        .HasColumnType("integer");

                    b.Property<float?>("HeartRate")
                        .HasColumnType("real");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QueueModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ServiceStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("SpO2")
                        .HasColumnType("real");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("TriageCategory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EncounterId");

                    b.HasIndex("ArrivalTime");

                    b.HasIndex("PatientId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("EDMS.Core.Domain.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveProblems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllergiesList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsJohnDoe")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PatientId");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("EDMS.Core.Domain.QueueAlert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualWqHours")
                        .HasColumnType("double precision");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<double>("ThresholdMinutes")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlertId");

                    b.HasIndex("AlertType", "TriggeredAt");

                    b.ToTable("QueueAlerts");
                });

            modelBuilder.Entity("EDMS.Core.Domain.QueueModel", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DefaultSigmaA2")
                        .HasColumnType("double precision");

                    b.Property<double?>("DefaultSigmaS2")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceDistribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModelId");

                    b.HasIndex("ModelType")
                        .IsUnique();

                    b.ToTable("QueueModels");
                });

            modelBuilder.Entity("EDMS.Core.Domain.QueueSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CaSquared")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CsSquared")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cv")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<double>("L")
                        .HasColumnType("double precision");

                    b.Property<double>("Lambda")
                        .HasColumnType("double precision");

                    b.Property<double>("Lq")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<double>("Mu")
                        .HasColumnType("double precision");

                    b.Property<double>("Rho")
                        .HasColumnType("double precision");

                    b.Property<double?>("SigmaA2")
                        .HasColumnType("double precision");

                    b.Property<double?>("SigmaS2")
                        .HasColumnType("double precision");

                    b.Property<double>("W")
                        .HasColumnType("double precision");

                    b.Property<double>("Wq")
                        .HasColumnType("double precision");

                    b.HasKey("SnapshotId");

                    b.HasIndex("ModelId", "ComputedAtUtc");

                    b.ToTable("QueueSnapshots");
                });

            modelBuilder.Entity("EDMS.Core.Domain.Resource", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OccupiedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ResourceId");

                    b.HasIndex("ResourceType");

                    b.HasIndex("Status");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("EDMS.Core.Domain.StaffUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("StaffUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
